import { AutresConducteurs, InfosConducteur } from "../dto/create-assurance-vehicule.dto";

export interface InfosAssuranceVehicule {
    type_vehicule: string,
    marque: string,
    modele: string,
    couleur_carrosserie: string,
    immatriculation: string,
    date_mise_en_circulation: string,
    date_achat: string,
    chevaux_fiscaux: number,
    puissance: number,
    energie: string,
    usage: string,
    kilometrage_annuel: number,
    kilometrage_actuel: number,
    lieu_stationnement: string,
    conducteur_principal: InfosConducteur,
    conducteurs_secondaires: AutresConducteurs,
    bonus_malus: number,
    suspension_5_dernieres_annees: boolean,
    annulation_5_dernieres_annees: boolean,
    nombre_sinistres_24_derniers_mois: number,
    date_derniers_sinistres: string,
    nature_sinistre: string,
    formule_choisie: string,
    franchise: number,
    assistances: [],
}
