
export interface InformationsAssuranceHabitation {
    "type_logement": string,
    "etage_appartement": number,
    "date_enmenagement": string,
    "proprietaire": boolean,
    "locataire": boolean,
    "residence_principale": boolean,
    "residence_secondaire": boolean,
    "periode_inhabitation": string,
    "estimation_capital": number,
    "resiliation_3_dernieres_annees": boolean,
    "nombre_sinistres_3_dernieres_annees": number,
    "logement_professionnel": boolean,
    "personnes_foyer": number,
    "enfants_foyer": number,
    "anciennete_logement": number,
    "surface_habitable": number,
    "nombre_pieces": number,
    "type_chauffage": string,
    "equipement_protection": string,
    "equipement_logement": string,
}